url: https://deb72.github.io/Cookie/
baseurl: /

# Site settings
title: Deb's Cookie Designs
email: debscookiedesigns@gmail.com
description: "Decorated Cookies for DFW/Denton TX area"


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: http://instagram.com/debscookiedesigns



# Build settings
markdown: kramdown
permalink: pretty
